# This will run on Travis' 'new' container-based infrastructure
# sudo: required
# dist: trusty

sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: Clayer
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/yogeshg/clayer.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      # - g++-6
      # - gcc-6

# Build your code e.g. by calling make
script:
  - echo "dummy make"

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x genDocsAndDeploy.sh
  - ./genDocsAndDeploy.sh
